name: Test

on:
  pull_request:
    branches: [develop]
  push:
    branches: [main]
concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    environment: development

    strategy:
      matrix:
        node: [16.x]
        os: [ubuntu-latest]

    env:
      CHROME_MAC: ${{vars.CHROME_MAC}}
      CHROME_WIN: ${{vars.CHROME_WIN}}
      CHROME_LINUX: ${{vars.CHROME_LINUX}}

    name: Test - ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
